version: '3'
services: 
  proxy:
    container_name: proxy
    image: nginx
    ports:
      - "80:80"
    volumes:
      - $PWD/html/:/etc/nginx/html/
      - $PWD/config/:/etc/nginx/conf.d/
    networks: 
      - backend
  webapp:
    container_name: webapp
    image: tutum/hello-world
    networks: 
      - backend
networks: 
  backend: